<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Cheari.Controls</RootNamespace>
    <AssemblyName>Cheari.Controls.Chart</AssemblyName>
    <LangVersion>latest</LangVersion>
    <!-- 关键：确保生成 XML 文档文件，有时有助于设计器识别 -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.Mathematics" Version="2.1.1" />
    <PackageReference Include="Vortice.Wpf" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Cheari.Controls.Chart.Icon.bmp" />
  </ItemGroup>



</Project>
